### ISSUE TITLE
Seems the new map controls are no longer up on staging maps

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/outerspatial-map-library#52] opened 2017-09-27 20:22 UTC
https://staging.outerspatial.com/builder_maps/23/embed#11/37.3199/-122.1165

![screen shot 2017-09-27 at 1 21 39 pm](https://user-images.githubusercontent.com/2602563/30935853-d4fcd770-a386-11e7-81b7-4c4b0e324861.png)

**Comment by nateirwin** [comment] 2017-09-28 14:33
Duplicate of #51, which has been closed.

**Closed by nateirwin** 2017-09-28 14:33 UTC
